sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_628e5a5f406b_key -iv $encrypted_628e5a5f406b_iv -in sa.json.enc -out sa.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file sa.json
  - gcloud config set project hitcount
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials standard-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u svladimirovich --password-stdin
deploy:
  provider: script
  script: bash ./deploy-to-k8s.sh
  on:
    branch: master