apiVersion: v1
kind: Pod
metadata:
  name: counter-pod
  labels:
    id: hit-counter-web
spec:
  containers:
    - name: hit-count
      image: svladimirovich/hit-count
      ports:
        - containerPort: 3000